language: python

python:
  - "3.5"

sudo: required

before_install:
  # Setup conda (needed for opencv, ray dependency)
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - export TEST_FLAG="True"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install python=3.5.2  # to match conda environment
  - python -V

  # python library dependencies (not affected by choice of OS)
  - pip install tensorflow
  - pip install gym==0.10.5
  - pip install flake8 .

install:
  # Setup ray from https://s3-us-west-2.amazonaws.com/ray-wheels/
  - pip install https://s3-us-west-1.amazonaws.com/flow.utils/ray-0.5.0-cp36-cp36m-manylinux1_x86_64.whl

  # Copy over local rllib changes (testing branch)
  - pushd $HOME/build/flow-project
  -     git clone https://github.com/eugenevinitsky/ray.git
  -     cd ray && git fetch && git checkout master && cd ..
  -     pushd ray
  -         RAY_SITE_DIR=`python -c "import ray; print(ray.__path__[0])"`
  -         rm -rf $RAY_SITE_DIR/rllib
  -         ls $RAY_SITE_DIR
  -         cp -r python/ray/rllib $RAY_SITE_DIR/rllib
  -     popd
  - popd

  # [sumo] dependencies and binaries
  - sudo apt-get update
  - sudo apt-get install -y subversion autoconf build-essential libtool
  - sudo apt-get install -y libxerces-c3.1 libxerces-c3-dev libproj-dev
  - sudo apt-get install -y proj-bin proj-data libgdal1-dev libfox-1.6-0
  - sudo apt-get install -y libfox-1.6-dev
  #  [sumo] Add python tools and sumo binaries
  - pushd $HOME/build/flow-project/flow
  -     scripts/setup_sumo_ubuntu1404.sh
  - popd

  - ls ../

before_script:
  - flake8 --show-source

script:
  - nose2
